# Generated by Django 4.2.2 on 2023-09-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_department_itemsforsale_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='book',
            new_name='item',
        ),
    ]
