# Generated by Django 4.2.2 on 2023-09-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_book_cartitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsforsale',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
