# Generated by Django 4.2.2 on 2023-09-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_bookforsale_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('offer', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(default='No description provided')),
                ('preview_1', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('preview_2', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('preview_3', models.ImageField(blank=True, null=True, upload_to='book_images')),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.itemsforsale'),
        ),
        migrations.DeleteModel(
            name='BookForSale',
        ),
    ]
